services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: memoria_backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/templates:/app/templates:ro
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
        NEXT_PUBLIC_ADMIN_BASE_URL: http://localhost:3002
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:3001
    container_name: memoria_frontend
    env_file:
      - ./frontend/.env
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
        NEXT_PUBLIC_APP_BASE_URL: http://localhost:3000
        NEXT_PUBLIC_ADMIN_BASE_URL: http://localhost:3002
        NEXT_PUBLIC_INFO_BASE_URL: http://localhost:3004
        NEXT_PUBLIC_HELP_BASE_URL: http://localhost:3003
        NEXT_PUBLIC_APP_ENV: development
    container_name: memoria_auth
    env_file:
      - ./auth/.env
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
        NEXT_PUBLIC_APP_BASE_URL: http://localhost:3000
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:3001
    container_name: memoria_admin
    env_file:
      - ./admin/.env
    environment:
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - backend

  help:
    build:
      context: ./help
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:3001
    container_name: memoria_help
    env_file:
      - ./help/.env
    environment:
      PORT: 3003
    ports:
      - "3003:3003"
    depends_on:
      - backend

  info:
    build:
      context: ./info
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
        NEXT_PUBLIC_AUTH_BASE_URL: http://localhost:3001
    container_name: memoria_info
    env_file:
      - ./info/.env
    environment:
      PORT: 3004
    ports:
      - "3004:3004"
    depends_on:
      - backend
